name: CI-CHECKS

on: [push]

jobs:
  run-phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Run PHPCodesniffer
        run: ./vendor/bin/phpcs -p -s --standard=phpcs.xml src tests
  run-php-stan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon.dist
  run-php-unit-tests:
    needs: [run-phpcs, run-php-stan]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Execute tests
        run: vendor/bin/phpunit -c phpunit.xml --colors=always --verbose --testdox
  run-assemble-php-unit-coverage:
    needs: [run-php-unit-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: Run PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5.28
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          report: ./clover.xml
          coverage_badge_path: 'badge.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}